# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "ubuntu-11.10"

  config.vm.network :bridged

  config.vm.provision :puppet 

  config.vm.forward_port 6379, 9191
end
